# Application URLs
base.url=https://www.saucedemo.com
api.base.url=https://reqres.in/api

# Browser config
browser=chrome
headless=false

# Test credentials
valid.username=standard_user
valid.password=secret_sauce
invalid.username=locked_out_user
invalid.password=wrong_password

# reqres api key
api.key=reqres_5347163775524266b1b46648c6679e16